version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0

  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "19000:19000"
    environment:
      - NODE_ENV=production

networks:
  pidocs-network:
    driver: bridge
